services:
  db:
    image: 'postgres:17'
    container_name: ASSET-DB
    hostname: asset-db
    security_opt:
      - 'no-new-privileges:true'
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - asset
        - '-U'
        - assetuser
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - ./db:/var/lib/postgresql/data  # Changed from /volume/docker/asset/db
    environment:
      POSTGRES_DB: asset
      POSTGRES_USER: assetuser
      POSTGRES_PASSWORD: assetpass
    restart: 'on-failure:5'
  asset:
    image: 'zurielbax/asset-rpo:dev'
    container_name: asset
    ports:
      - "8080:80"
    volumes:
      - './asset/data:/data:rw'
      - './asset/conf:/conf:rw'
    environment:
      PHP_TZ: America/New_York
      TIMEZONE: America/New_York
      PUID: 1000
      PGID: 1000
      APP_NAME: Mariushosting
      APP_KEY: 'base64:PqkYgeKqq3hdHZTvL6ENXdhgyyoCDZYj9wofOcw0l4o='
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: 'http://127.0.0.1'
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: asset
      DB_USERNAME: assetuser
      DB_PASSWORD: assetpass
      DB_PASSWORD_FILE: rootpass
      CACHE_STORE: file
      SESSION_DRIVER: file
      SESSION_LIFETIME: 240
      SESSION_ENCRYPT: false
      SESSION_PATH: /
      SESSION_DOMAIN: null
      SANCTUM_STATEFUL_DOMAINS: '127.0.0.1'
      STARTUP_DELAY: 5
      TRUSTED_PROXIES: '*'
    restart: 'on-failure:5'
    depends_on:
      db:
        condition: service_healthy
