#!/bin/bash

main() {

    prepare_file_permissions
    run_npm_build
    prepare_storage
    wait_for_db
    run_migrations
    optimize_app
    run_server "$@"

    echo "**** Startup file Finished ****"
}

prepare_file_permissions() {
    chmod a+x ./artisan
}

run_npm_build() {
    echo "Installing NPM dependencies"
    if [ -f "package.json" ]; then
        echo "Running NPM clean install"
        npm ci

        echo "Running NPM build"
        npm run build
    else
        echo "No package.json found, skipping NPM build"
    fi
}

prepare_storage() {
    # Create required directories for Laravel
    mkdir -p /usr/share/nginx/html/storage/framework/cache/data
    mkdir -p /usr/share/nginx/html/storage/framework/sessions
    mkdir -p /usr/share/nginx/html/storage/framework/views

    # Set permissions for the storage directory and public directory
    chown -R www-data:www-data /usr/share/nginx/html/storage
    chown -R www-data:www-data /usr/share/nginx/html/public  # Added public directory permissions
    chmod -R 775 /usr/share/nginx/html/storage
    chmod -R 775 /usr/share/nginx/html/public  # Added public directory permissions

    # Ensure the symlink exists
    php artisan storage:link
}

wait_for_db() {
    echo "Waiting for DB to be ready"
    until ./artisan migrate:status 2>&1 | grep -q -E "(Migration table not found|Migration name)"; do
        sleep 1
    done
}

run_migrations() {
    ./artisan migrate --force

}

optimize_app() {
    ./artisan optimize:clear
    ./artisan optimize
}

run_server() {
    # Start Nginx
    nginx

    # Start PHP-FPM in foreground
    exec php-fpm -F
}

main "$@"
